server:
  port: 443
  ssl:
    key-store-type: PKCS12
    key-store: "classpath:keystore/app.p12"
    key-store-password: "appapp"
    enabled: true

spring:
  datasource:
    url: "jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;INIT=CREATE SCHEMA IF NOT EXISTS numero;"
    username: sa
    password:
